% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt,
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
    \setmainfont[]{Times New Roman}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{2}
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{caption}
\usepackage{anyfontsize}
\KOMAoption{captions}{tableheading}
\numberwithin{figure}{section}
\numberwithin{table}{section}
\usepackage{etoolbox}
\makeatletter
\patchcmd{\maketitle}{\thispagestyle{plain}}{\thispagestyle{plain}\newpage}{}{}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Bridging the Gap:},
  pdfauthor={Brock Akerman, Hanan Ali, Taylor Cesarski},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Bridging the Gap:}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Comparing Employer and Educator Expectations in Small Animal
Dentistry}
\author{Brock Akerman, Hanan Ali, Taylor Cesarski}
\date{2025-07-28}

\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}

\newpage

\section{Introduction}\label{introduction}

Dr.~Mariea Ross-Estrada, a faculty member at North Carolina State
University's College of Veterinary Medicine, is exploring whether there
are differences between the expectations of small animal primary care
veterinary employers and veterinary educators regarding new graduates'
competencies in dentistry. Through her own professional experience and
conversations with colleagues, Dr.~Ross-Estrada observed that many
veterinarians must rely on on-the-job training to gain the skills
necessary in small animal dentistry. These shared experiences prompted
her to investigate whether there is a misalignment in what is taught in
veterinary programs and what is expected in clinical practice.

To explore this question, Dr.~Ross-Estrada distributed two surveys: one
to medical directors and private practice owners and the other to
primary care veterinary educators. Both surveys included similar
questions regarding what early-career veterinarians are expected to have
learned during their education and the skills they are expected to
perform in practice.

This research has the potential to improve veterinary care by ensuring
new graduates are better prepared to meet clinical demands. It could
also support a smoother transition into practice for early-career
veterinarians, reduce the burden of on-the-job training for employers,
and promote overall workforce readiness in the field of small animal
primary care.

\subsection{Research Question}\label{research-question}

How do small animal primary care employers (medical directors and
practice owners) and primary care veterinary educators differ in regards
to their expectations of early career veterinary graduates' competencies
in small animal dentistry?

\subsection{Statistical Questions}\label{statistical-questions}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Are there significant differences between educators and practice
  owners in their belief that new graduates are competent in key dental
  skills on their first day of practice?
\item
  Is there a difference between educators and practice owners in their
  reports (educators' actual teaching vs.~owners' perceptions) of which
  dental skills were taught in the pre-clinical DVM curriculum for
  recent graduates?
\item
  Is there a difference between educators and practice owners in their
  level of agreement about whether specific dental skills should be
  taught pre-clinically?
\item
  Do employers and educators differ in their expectations about how many
  dental procedures new graduates should complete during clinical
  training?
\item
  Is there difference between the instructional formats in dentistry
  reported by DVM programs and the formats perceived by employers to
  have been completed by early career veterinarians?
\item
  Do educators and employers differ in their views on which formats of
  clinical instruction in dentistry should be required for DVM students
  as part of their clinical training?
\item
  Is there a difference between the clinical dentistry skills that
  educators report DVM students are learning during their clinical
  training and the skills that employers believe recent graduates have
  completed as part of their DVM program?
\item
  Do educators and employers differ in their opinions about which
  clinical dentistry skills DVM students should be required to practice
  or learn during their clinical training?
\end{enumerate}

\section{Data}\label{data}

\subsection{Data Description}\label{data-description}

Two separate surveys were administered to mutually exclusive groups:
veterinary employers who have worked with students, and educators who
have taught students. There was no overlap between these groups and they
can be assumed to be independent.

The employer data set consists of responses from 29 participants
answering 40 questions, while the educator data set includes 43
participants answering 34 questions. Each group was asked a single
qualifying question to determine eligibility for participation, along
with nine questions covering demographics and institutional context.
Educators were then presented with 24 competency and sentiment-based
questions, while employers answered 30 such items focused on
professional expectations and training in veterinary medicine.

Survey questions took several forms. Some were binary (Yes/No),
particularly those related to demographics and institutional
affiliation. Others used a ``select all that apply'' format, commonly
seen in questions asking respondents to identify procedures performed at
their practice. Many of these questions were followed by Likert-scale
items. The Likert scales were even-numbered and omitted a neutral
option, which may have contributed to at least two instances where
respondents selected both ``agree'' and ``disagree'' for the same item.

Several questions offered an ``Other'' response with a text box for
elaboration. A few required numeric input, such as estimates of hours
worked or the number of practicing veterinarians. These integer fields
were not restricted by any upper bound, regardless of contextual
reasonableness.

\paragraph{Global survey session
metrics}\label{global-survey-session-metrics}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{Final-Project_files/figure-pdf/Data_Desc_01-1.pdf}}

}

\caption{Assessing survey elapsed time distribution via box plots to
understand engagement by survey group.}

\end{figure}%

Survey completion time differed by group. Educators, on average, spent
more time completing the survey than employers. While no follow-up
question asked participants to explain their response time, this
discrepancy may reflect greater engagement or a tendency for more
elaborated responses among educators. It may also suggest a greater
willingness among educators to participate more thoughtfully. The box
plot above illustrates the distribution of survey duration (in minutes)
by group.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{Final-Project_files/figure-pdf/Data_Desc_02-1.pdf}}

}

\caption{Assessing survey completion as a density curve to understand
engagement by survey group.}

\end{figure}%

Regarding the proportion of the survey completed, employer responses
were more variable---spanning the full range from partial to full
completion. In contrast, educators tended to complete more of the
survey, with a concentration near full completion and a less pronounced
left tail. The density plot above visualizes these differences in survey
progress across groups.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{Final-Project_files/figure-pdf/Data_Desc_03-1.pdf}}

}

\caption{Geographic distribution of survey respondents across the United
States.}

\end{figure}%

Our analysis focused only on those responses from the United States.
Using the metadata that came with the Qualtric survey output, we were
able to leverage geographical datapoints and eliminate three responses
from our working dataset. Employer survey participants were
predominantly sampled from locations along the eastern seaboard of the
United States, while educators were more widely distributed across the
country. We highlight this to illustrate that perceptions of veterinary
dental students---particularly among employers---may differ for
individuals located far from the regions where most participants were
sampled. Additionally, because many of the responses came from major
metropolitan areas, it is possible that our findings may underrepresent
sentiments regarding student knowledge gaps in rural locations.

\paragraph{Educator metrics}\label{educator-metrics}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{Final-Project_files/figure-pdf/Data_Desc_04-1.pdf}}

}

\caption{Educator contextualized background information about teaching
and procedures.}

\end{figure}%

Figure 3.4 provides an overview of the survey participants and their
institutions. Most respondents reported having between 2 and 4 years of
experience teaching veterinary students in clinical training. The
distribution of years taught appears approximately normal, with fewer
educators at the lower and upper ends of the experience range.
Respondents also reported the number of dental procedures performed by
their primary care service each week. While some outliers from busier
institutions reported higher volumes, most educators estimated
performing between 1 and 8 procedures per week.

\paragraph{Employer metrics}\label{employer-metrics}

The employer dataset was considerably smaller than the educator dataset,
which may reflect differences in motivation or willingness to complete
the survey. Most employer respondents identified as practice owners, and
approximately 75\% indicated they were employed in private practice.
This aligns with findings from the American Veterinary Medical
Association (AVMA), which reported that ``most veterinarians age 75 or
younger, 83.9\%, work in private clinical practice'' (American
Veterinary Medical Association 2019).

\begin{longtable}[]{@{}lrr@{}}
\caption{Job Setting or Organization: Counts and
Percentages}\tabularnewline
\toprule\noalign{}
Job Setting & Count & Percentage \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Job Setting & Count & Percentage \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Group corporate veterinary practice & 2 & 16.7 \\
Independently owned group veterinary practice & 2 & 16.7 \\
Independently owned single veterinary practice & 7 & 58.3 \\
Industry/commercial & 1 & 8.3 \\
\end{longtable}

\begin{longtable}[]{@{}lrr@{}}
\caption{Respondent Role: Counts and Percentages}\tabularnewline
\toprule\noalign{}
Respondent Role & Count & Percentage \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Respondent Role & Count & Percentage \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Associate veterinarian & 2 & 18.2 \\
Practice manager/HR representative & 2 & 18.2 \\
Practice owner & 7 & 63.6 \\
\end{longtable}

Survey responses were also heavily skewed toward practice ownership,
with 63.6\% of employer participants identifying as owners. By
comparison, the same AVMA survey reported that only 21.3\% of
veterinarians identified as practice owners. This discrepancy may be due
to the smaller sample size or the possibility that practice owners were
more willing to complete the survey than associates or other veterinary
professionals.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{Final-Project_files/figure-pdf/Data_Desc_07-1.pdf}}

}

\caption{Average dental procedures employer survey participants
indicated they performed each week.}

\end{figure}%

Figure 3.5 shows that procedure counts tend to be lower in the employer
group compared to the educator group, although the overall distribution
shapes are similar. In both groups, the data exhibit a right-skewed
pattern, with most respondents reporting lower procedure counts and a
few outliers representing higher volumes. This pattern aligns with the
intuitive understanding that while some practices or institutions have
greater clinical demands on veterinarians, these cases are less
common---at least based on the survey responses.

\subsection{Data Source}\label{data-source}

Survey data were collected using Qualtrics, a cloud-based experience
management platform commonly used for gathering feedback and sentiment
across workforce domains. Participants from the educator survey were
recruited via email invitation sent by the researcher, using
pre-existing contact lists. Dr.~Ross-Estrada distributed the employer
survey to her personal and professional networks online. Participation
was voluntary and anonymous. There was no incentive offered for
completing the survey.

\subsection{Preprocessing Description}\label{preprocessing-description}

Although the employer and educator data sets shared a similar structure,
they were not identical. Most pre-processing steps were applied
uniformly across both data sets, with minor deviations where needed.

The data sets were imported into the RStudio environment (version
2024.04.1 Build 748). A new variable was created to label the data
source (``Educator'' or ``Employer'') for later grouping and
visualization. The existing respondent\_id column served as a unique
identifier and was treated as the primary key.

Initial cleaning involved removing extraneous metadata included by
Qualtrics---such as survey start and end times, IP addresses,
geolocation data, and question display logic---all of which were
irrelevant to the analysis. These columns were trimmed to streamline the
dataset for subsequent transformation and statistical work.

Column names in the original Qualtrics export were alphanumeric but
often ambiguous and misleading. Many variable names did not match the
corresponding survey question numbers. Our team manually mapped the
exported column names to their corresponding survey questions and
responses by referencing adjacent metadata fields and using deductive
reasoning. This process allowed us to build an index-based column naming
structure, which greatly improved the manageability and interpretability
of the dataset.

Before diving into question-specific analysis, we first identified the
subset of survey questions relevant to our research objectives. All
unrelated or out-of-scope items were removed. This step reduced the
employer dataset from 176 columns to 100, and the educator dataset from
171 columns to 102.

Several formatting inconsistencies also needed to be resolved. Some
multi-select questions appeared in the form of comma-separated text
responses within a single column, while others were exported into
multiple binary columns. Additionally, for certain questions, a response
option that received zero selections was dropped entirely by Qualtrics.
To standardize these issues, we implemented a script to ``explode''
comma-separated responses into individual binary columns. For dropped
columns, we manually reintroduced them as zero-filled dummy variables to
preserve the full response structure.

Finally, we filtered out participants who answered less than half of the
survey. We also excluded:

\begin{itemize}
\item
  Employers who responded ``No'' to the question: ``Do you work with
  early career veterinarians (someone who has graduated from a DVM
  program after May 2021)?''
\item
  Educators who responded ``No'' to: ``Do you teach in any capacity of
  the dental curriculum at your institution?''
\end{itemize}

After all preprocessing steps, the final cleaned datasets consisted of
13 employer participants and 30 educator participants.

\section{Statistical Methods}\label{statistical-methods}

\paragraph{Likert scale questions (statistical questions \#1,3, 6, and
8)}\label{likert-scale-questions-statistical-questions-13-6-and-8}

These questions use a Likert scale with response options: Strongly
Agree, Agree, Disagree, and Strongly Disagree across a variety of skills
and procedures. Given the ordinal nature of these responses, we will use
diverging stacked bar charts and summary tables to visually explore the
data. We will then use Mann-Whitney U Tests for formal hypothesis
testing differences between groups. Finally, a Ranked-Biserial
Correlation (RBC) of effect size to find direction and magnitude of
differences between groups.

The Mann-Whitney U Test is a non-parametric test used to assess whether
there is a statistically significant difference in the distributions of
ordinal or continuous variables between two independent groups. In this
case, educators and employers are assumed to be independent, consistent
with the survey design.

This test is appropriate for Likert-scale data because:

\begin{itemize}
\tightlist
\item
  It does not assume normality (unlike the t-test),
\item
  It respects the ordinal (ranked) structure of the data,
\item
  It retains statistical power in small samples.
\end{itemize}

\begin{longtable}[]{@{}lrrr@{}}
\caption{Mann-Whitney U Rank Summary Table}\tabularnewline
\toprule\noalign{}
Group & Sample.Size & Sum.of.Ranks & Mean.Rank \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Group & Sample.Size & Sum.of.Ranks & Mean.Rank \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Group 1 (e.g., Educators) & n₁ & R₁ & R₁ / n₁ \\
Group 2 (e.g., Employers) & n₂ & R₂ & R₂ / n₂ \\
\end{longtable}

In order to calculate the test statistic and p-value for a Mann-Whitney
U Test:

\begin{itemize}
\tightlist
\item
  All observations are ranked together
\item
  The sum of the ranks for each group is calculated (\(R_1\) and
  \(R_2\))
\item
  The test statistic U is then calculated as the minimum of \(U_1\) and
  \(U_2\) where \(U_1\) and \(U_2\) are the following:
  \(U_1 = R_1 - \frac{n_1(n_1 + 1)}{2},  U_2 = R_2 - \frac{n_2(n_2 + 1)}{2}\)
\item
  Then the p-value is calculated from the U distribution or normal
  approximation.
\end{itemize}

To complement the Mann-Whitney U tests, effect sizes were calculated
using the rank-biserial correlation (RBC). While the p-value assesses
whether a statistically significant difference exists between groups,
the rank-biserial correlation quantifies the magnitude and direction of
that difference---adding a layer of practical interpretation. An RBC
value near 0 suggests little to no effect, while values near -1 or 1
suggest large differences favoring one group over the other.

Formally, the RBC is calculated directly from the Mann-Whitney U
statistic:

\(r_{rb} = \frac{2U}{n_1n_2} - 1\)

Where:

\begin{itemize}
\tightlist
\item
  \(U\) is the Mann-Whitney U statistic (typically the smaller of
  \(U_1\) and \(U_2\))\\
\item
  \(n_1\) and \(n_2\) are the sample sizes of the two independent groups
\end{itemize}

This formula scales \(U\) into the \([-1,1]\) interval, where:

\begin{itemize}
\tightlist
\item
  \(r_{rb} = 0\) implies overlapping ranks (no difference)\\
\item
  \(r_{rb} = 1\) implies every value in group 1 exceeds every value in
  group 2\\
\item
  \(r_{rb} = -1\) implies every value in group 2 exceeds every value in
  group 1
\end{itemize}

\(U\) is derived by jointly ranking all observation across groups. The
sum or ranks (\(R_1\) and \(R_2\)) are then used to calculate:

\(U_1 = R_1 - \frac{n_1(n_1+1)}{2}\),\\
\(U_2 = R_2 - \frac{n_2(n_2+1)}{2}\)

Then U = min(\(U_1\),\(U_2\)) and this value is substituted for
\(r_{rb}\).

P-values and an RBC value will be applied to each statistical question
listed above in order to formally analyze the data.

\paragraph{Select all that apply questions (statistical questions \#2,
5, and
7)}\label{select-all-that-apply-questions-statistical-questions-2-5-and-7}

These questions asked the participants to ``select all that apply'' as
it relates to skills in pre-clinical curriculum, format of dental
instruction, and skills for clinical training respectively. We will
utilize frequency tables and bar plots to explore the data for these
questions and use Fisher's Exact Test as a formal inference procedure
for the comparison of the two groups. Dot plots will also be utilized
for questions with many options to avoid crowding in bar graphs.

Fisher's Exact Test works with categorical data with independent
samples, in this case educators and employers. Based on the survey
design from the client, it is again reasonable to assume that these two
groups are independent. In this context, Fisher's Exact Test is
preferred over Chi-Squared Tests due to the small sample size and
therefore not meeting the expected count threshold that is required to
proceed with Chi-Squared Tests.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3288}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2192}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2055}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2466}}@{}}
\caption{Fisher's Exact 2×2 Contingency Table}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Group
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Outcome.Present
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Outcome.Absent
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Row.Totals
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Group
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Outcome.Present
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Outcome.Absent
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Row.Totals
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Group 1 (ex: Educators) & a & b & a + b \\
Group 2 (ex: Employers) & c & d & c + d \\
Column Totals & a + c & b + d & n = a + b + c + d \\
\end{longtable}

Fisher's Exact Test operates under the null hypothesis that there is no
association between the two variables. The alternative hypothesis is
that there is an association. The p-value for the test is computed using
the following formula:

\[p = \frac{(a+b)! \, (c+d)! \, (a+c)! \, (b+d)!}{a! \, b! \, c! \, d! \, n!}\]

P-values are then computed for each skill, format, etc. between the two
groups (educators and employers) depending on the statistical question
to be analyzed.

\paragraph{Numerical entry questions: (statistical question
\#4)}\label{numerical-entry-questions-statistical-question-4}

This question asks participants to enter a number related to the number
of dental procedures that should be completed during training in
different areas. We plan to produce box plots and/or histograms to
visually examine the data. Depending on the normality or lack thereof of
the distributions, we will then conduct either a two-sample t-test or a
Mann-Whitney U Test. As mentioned above, the Mann Whitney U test is a
non-parametric test that does not depend on the assumption of normality.
If the assumption on normality is met, we can consider a two-sample t
test for this analysis. However, from examination of the data, normality
is not met and we will therefore utilize a Mann-Whitney U Test. The test
follows the same method above as statistical questions \#2, 5, and 7.

\section{Results}\label{results}

\subsection{Statistical Analysis}\label{statistical-analysis}

\subsubsection{S1 Are there significant differences between educators
and practice owners in their belief that new graduates are competent in
key dental skills on their first day of
practice?}\label{s1-are-there-significant-differences-between-educators-and-practice-owners-in-their-belief-that-new-graduates-are-competent-in-key-dental-skills-on-their-first-day-of-practice}

To assess whether there are differences in perceptions of new graduate
competence in dentistry, educators and employers were asked a parallel
question (Q4). Employers were asked to rate their expectation that early
career veterinarians can competently perform 12 specific dental skills
on their first day of employment. Educators were asked to rate whether
they believe new graduates can perform those same skills competently.
Responses were recorded on a 4-point Likert scale from 1 (Strongly
Disagree) to 4 (Strongly Agree).

We used the Mann-Whitney U test to compare educator and employer
responses for each skill, as this non-parametric test is well-suited for
ordinal data from two independent groups. In addition to p-values, we
calculated the ranked-biserial correlation (r\_rb) to assess effect
sizes and provide insight into the magnitude and direction of observed
differences. Results are summarized with median ratings for each group,
sample sizes, and effect size interpretations (e.g., small, medium,
large). Significance stars were added to highlight results below
conventional thresholds (e.g., p \textless{} 0.05), and results were
sorted by p-value to aid interpretation.

\begin{table}[!h]
\centering
\caption{Mann-Whitney U-Test Results for Competency Ratings}
\centering
\resizebox{\ifdim\width>\linewidth\linewidth\else\width\fi}{!}{
\begin{tabular}[t]{ccccccc}
\toprule
Skill & Med (Edu) & Med (Emp) & N (Edu / Emp) & P-Value & r\_rb & Interpretation\\
\midrule
\cellcolor{gray!10}{Periodontal probing} & \cellcolor{gray!10}{4} & \cellcolor{gray!10}{4} & \cellcolor{gray!10}{28 / 13} & \cellcolor{gray!10}{1.000} & \cellcolor{gray!10}{0.00} & \cellcolor{gray!10}{Negligible effect}\\
Dental radiography - positioning & 3 & 2 & 27 / 12 & 0.369 & 0.18 & Small positive effect\\
\cellcolor{gray!10}{Dental radiography - interpretation} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{28 / 12} & \cellcolor{gray!10}{0.052 .} & \cellcolor{gray!10}{0.36} & \cellcolor{gray!10}{Medium positive effect}\\
Scaling & 4 & 4 & 27 / 13 & 0.552 & -0.10 & Negligible effect\\
\cellcolor{gray!10}{Polishing} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{28 / 13} & \cellcolor{gray!10}{0.242} & \cellcolor{gray!10}{0.21} & \cellcolor{gray!10}{Small positive effect}\\
\addlinespace
Simple extractions - canine & 3 & 3 & 28 / 13 & 0.374 & 0.16 & Small positive effect\\
\cellcolor{gray!10}{Simple extractions - feline} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{3} & \cellcolor{gray!10}{28 / 13} & \cellcolor{gray!10}{1.000} & \cellcolor{gray!10}{0.00} & \cellcolor{gray!10}{Negligible effect}\\
Open extractions - canine (single root) & 3 & 3 & 28 / 13 & 0.769 & -0.06 & Negligible effect\\
\cellcolor{gray!10}{Open extractions - feline (single root)} & \cellcolor{gray!10}{2} & \cellcolor{gray!10}{2} & \cellcolor{gray!10}{27 / 13} & \cellcolor{gray!10}{0.613} & \cellcolor{gray!10}{-0.10} & \cellcolor{gray!10}{Negligible effect}\\
Open extractions - canine (multi-root) & 2 & 3 & 28 / 13 & 0.289 & -0.20 & Small negative effect\\
\addlinespace
\cellcolor{gray!10}{Open extractions - feline (multi-root)} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{1} & \cellcolor{gray!10}{7 / 4} & \cellcolor{gray!10}{0.778} & \cellcolor{gray!10}{-0.11} & \cellcolor{gray!10}{Small negative effect}\\
Fluoride treatment & 3 & 4 & 2 / 1 & 1.000 & -0.50 & Large negative effect\\
\bottomrule
\end{tabular}}
\end{table}

Overall, educators and employers had generally similar perceptions about
new graduate competence in most dental skills, with no statistically
significant differences observed at the conventional p \textless{} 0.05
threshold. However, some notable trends emerged. Dental radiography,
interpretation showed a borderline significant result (p = 0.052) with a
medium positive effect size (r\_rb = 0.36), suggesting that educators
may be slightly more confident than employers in new graduates' ability
to interpret dental radiographs. For most other skills, effect sizes
were negligible or small, and p-values were well above 0.05, indicating
no meaningful differences in perceived competence between groups. In a
few cases, such as open extractions, canine (multi-root), employers had
slightly higher confidence than educators (small negative effect size),
but again, these differences were not statistically significant. The
fluoride treatment item had a large effect size, but due to the very
small sample (2 educators, 1 employer), it is not meaningful or
generalizable.

\subsubsection{S2 Is there a difference between educators and practice
owners in their reports (educators' actual teaching vs.~owners'
perceptions) of which dental skills were taught in the pre-clinical DVM
curriculum for recent
graduates?}\label{s2-is-there-a-difference-between-educators-and-practice-owners-in-their-reports-educators-actual-teaching-vs.-owners-perceptions-of-which-dental-skills-were-taught-in-the-pre-clinical-dvm-curriculum-for-recent-graduates}

To evaluate whether differences exist between DVM educators and
employers in their understanding of which dental skills are taught in
the pre-clinical curriculum, we analyzed responses to parallel survey
questions. Educators were asked to indicate which of seven core
dentistry skills are taught as part of their pre-clinical courses (Q12),
while employers were asked which skills they believe recent graduates
were taught prior to clinical training (Q16). Since the two groups
answered different question numbers about the same underlying skills, we
first aligned the datasets by renaming employer variables to match
educator labels. This harmonization allowed for direct comparison of
responses skill-by-skill across the two groups.

After cleaning and reshaping the data into long format, we filtered out
invalid or missing entries and conducted Fisher's Exact Tests for each
skill. This non-parametric test is appropriate for evaluating
categorical (yes/no) outcomes in small samples, especially when
comparing proportions between two independent groups. Only skills for
which both groups provided non-missing responses were included in the
final analysis.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.4082}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.0816}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1122}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1122}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1429}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1429}}@{}}
\caption{Fisher's Exact Test Results by Skill}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Skill
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p\_value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_educator
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_employer
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
prop\_educator
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
prop\_employer
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Skill
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p\_value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_educator
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_employer
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
prop\_educator
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
prop\_employer
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Dental radiograph acquisition & 0.307 & 28 & 13 & 0.714 & 0.538 \\
Oral examination and charting & 0.399 & 28 & 13 & 0.786 & 0.923 \\
Simple extraction technique & 0.469 & 28 & 13 & 0.750 & 0.615 \\
Instrument identification and handling & 0.732 & 28 & 13 & 0.643 &
0.538 \\
Dental cleaning (scaling and polishing) & 0.742 & 28 & 13 & 0.536 &
0.615 \\
Local nerve blocks & 0.742 & 28 & 13 & 0.607 & 0.538 \\
Dental radiograph interpretation & 1.000 & 28 & 13 & 0.643 & 0.615 \\
\end{longtable}

Overall, educators and employers showed general agreement about which
dental skills are taught in the pre-clinical DVM curriculum, with no
statistically significant differences found across any of the seven
skills analyzed. Proportions of reported instruction were similar
between groups, with slight variations. For example, more educators than
employers reported that dental radiograph acquisition and simple
extraction techniques are taught, while more employers believed that
oral examination and charting and dental cleaning are included. However,
none of these differences reached significance, and all p-values were
well above 0.05. These findings suggest a shared but imperfect
understanding between groups, with minor discrepancies that are not
statistically meaningful.

\subsubsection{S3 Is there a difference between educators and practice
owners in their level of agreement about whether specific dental skills
should be taught
pre-clinically?}\label{s3-is-there-a-difference-between-educators-and-practice-owners-in-their-level-of-agreement-about-whether-specific-dental-skills-should-be-taught-pre-clinically}

To assess whether educators and employers differ in their beliefs about
which dental skills should be included in the pre-clinical DVM
curriculum, we analyzed responses to parallel Likert-scale questions:
Q13 (educators) and Q17 (employers). Both groups rated the importance of
teaching 12 specific dentistry skills using a 4-point Likert scale
ranging from 1 (Strongly Disagree) to 4 (Strongly Agree).

Because the data were ordinal and responses came from two independent
groups, the Mann-Whitney U test was used to compare educator and
employer ratings for each skill individually. This non-parametric test
is appropriate for comparing ordinal data between two independent
groups, especially when the assumptions for parametric tests may not
hold. Ratings were reshaped into long format and analyzed
skill-by-skill. The results table presents medians for each group,
sample sizes, p-values with significance indicators, effect size
estimates (rank-biserial correlation), and an interpretation of the
magnitude and direction of group differences.

\begingroup\fontsize{9}{11}\selectfont

\begin{longtable}[t]{>{\centering\arraybackslash}p{1.4in}>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.7in}>{\centering\arraybackslash}p{0.65in}>{\centering\arraybackslash}p{0.65in}>{\centering\arraybackslash}p{1.1in}}
\caption{Mann-Whitney U-Test Results for Pre-Clinical Dentistry Training}\\
\toprule
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{Median} & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{ } & \multicolumn{1}{c}{Effect Size} & \multicolumn{1}{c}{ } \\
\textbf{Skill} & \textbf{Med (Edu)} & \textbf{Med (Emp)} & \textbf{N (Edu / Emp)} & \textbf{P-Value} & \textbf{r\_rb} & \textbf{Interpretation}\\
\midrule
Open extractions - feline (multi-root) & 3 & 4 & 17 / 13 & 0.002 ** & -0.60 & Large negative effect\\
Fluoride treatment & 1 & 3 & 3 / 9 & 0.013 * & -1.00 & Large negative effect\\
Open extractions - canine (multi-root) & 4 & 4 & 26 / 13 & 0.079 . & -0.29 & Small negative effect\\
Open extractions - canine (single root) & 4 & 4 & 26 / 13 & 0.084 . & -0.29 & Small negative effect\\
Open extractions - feline (single root) & 4 & 4 & 27 / 13 & 0.093 . & -0.28 & Small negative effect\\
\addlinespace
Simple extractions - feline & 4 & 4 & 26 / 13 & 0.136 & -0.26 & Small negative effect\\
Dental radiography - interpretation & 4 & 4 & 28 / 12 & 0.164 & 0.13 & Small positive effect\\
Scaling & 4 & 4 & 28 / 13 & 0.403 & 0.14 & Small positive effect\\
Polishing & 4 & 4 & 28 / 12 & 0.480 & 0.12 & Small positive effect\\
Periodontal probing & 4 & 4 & 28 / 13 & 0.599 & 0.04 & Negligible effect\\
\addlinespace
Dental radiography - positioning & 4 & 4 & 27 / 11 & 0.726 & 0.07 & Negligible effect\\
Simple extractions - canine & 4 & 4 & 28 / 13 & 0.788 & -0.05 & Negligible effect\\
\bottomrule
\end{longtable}
\endgroup{}

Educators and employers generally agreed on the importance of teaching
core dental skills in the pre-clinical DVM curriculum, with most skills
receiving high median ratings (4 = Strongly Agree) from both groups.
However, statistically significant differences were observed for two
skills. Open extractions skill, feline (multi-root) showed a significant
difference (p = 0.002) with a large negative effect size (r\_rb =
-0.60), indicating employers placed greater importance on teaching this
skill than educators. Fluoride treatment also differed significantly (p
= 0.013) with a very large negative effect size (r\_rb = -1.00), though
the very small sample of educators (n = 3) limits interpretation.

Several other extraction-related skills showed small negative effect
sizes and borderline p-values, suggesting a trend toward employers
assigning slightly more importance to teaching advanced extractions
pre-clinically, though these differences did not reach statistical
significance. For all other skills, differences were negligible or
small, and p-values were well above 0.05, indicating broad consensus on
their pre-clinical importance.

\subsubsection{S4 Do employers and educators differ in their
expectations about how many dental procedures new graduates should
complete during clinical
training?}\label{s4-do-employers-and-educators-differ-in-their-expectations-about-how-many-dental-procedures-new-graduates-should-complete-during-clinical-training}

To assess whether educators and practice owners differ in their
expectations for the number of dental procedures students should
complete during clinical training, we compared responses from Question
19 of the educator survey and Question 24 of the employer survey.
Respondents indicated the number of procedures they believe should be
completed in four clinical settings: primary care, dentistry rotations,
shelter medicine, and lab animal medicine.

Before selecting an appropriate statistical test, we assessed normality
using the Shapiro-Wilk test, which showed that the data were not
normally distributed in any group-setting combination (all p-values
\textless{} 0.05). Given the non-normal distribution and the ordinal or
skewed nature of the data, we used the Mann-Whitney U test---a
non-parametric alternative to the independent samples t-test---to
compare the distributions of responses between educators and employers
for each clinical setting. This test is appropriate when comparing two
independent groups without assuming normality or equal variances.

\begin{table}
\caption*{
{\large \textbf{Mann-Whitney U Test: Expected Number of Dental Procedures}} \\ 
{\small Comparison of Educator and Employer Expectations by Clinical Setting}
} 
\fontsize{7.5pt}{9.0pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}cccccccc}
\toprule
Setting & Med (Edu) & Med (Emp) & N (Edu) & N (Emp) & P-Value & r\_rb & Effect Size \\ 
\midrule\addlinespace[2.5pt]
Dentistry\_Rotation & 4.0 & 6.5 & 24 & 10 & 0.080 . & -0.39 & Medium negative effect \\ 
Lab\_Animal & 0.0 & 0.0 & 16 & 9 & 0.222 & 0.24 & Small positive effect \\ 
Shelter\_Medicine & 2.0 & 0.0 & 19 & 9 & 0.235 & 0.27 & Small positive effect \\ 
Primary\_Care & 3.0 & 4.0 & 27 & 10 & 0.287 & -0.23 & Small negative effect \\ 
\bottomrule
\end{tabular*}
\end{table}

Educators and employers showed broad agreement on the number of dental
procedures that students should complete during clinical training, with
no statistically significant differences across the four clinical
settings evaluated. However, a notable trend was observed in the
dentistry rotation, where employers had higher expectations than
educators (median = 6.5 vs.~4.0), with a borderline p-value (p = 0.080)
and a medium negative effect size (r\_rb = -0.39), suggesting that
employers may expect more hands-on experience in this setting.

In the remaining settings---lab animal medicine, shelter medicine, and
primary care---differences in medians were small, and effect sizes were
negligible to small, with p-values well above 0.05, indicating no
meaningful disagreement between groups. These findings suggest that
while general expectations are aligned, employers may place slightly
greater emphasis on procedural experience in dedicated dentistry
rotations.

\subsubsection{S5 Is there difference between the instructional formats
in dentistry reported by DVM programs and the formats perceived by
employers to have been completed by early career
veterinarians?}\label{s5-is-there-difference-between-the-instructional-formats-in-dentistry-reported-by-dvm-programs-and-the-formats-perceived-by-employers-to-have-been-completed-by-early-career-veterinarians}

Both educators and employers were asked a question relating to the
format of instruction during the clinical year.

On question 20 of their survey, employers were asked: ``What format of
clinical instruction in dentistry do you believe that the early career
veterinarians (individuals who have graduated from a DVM program after
May 2021) hired into your practice/organization/institution completed as
part of their DVM training? Select all that apply.''

On question 16 of their survey, educators were asked: ``What format of
instruction in dentistry does your DVM program provide during the
clinical year? Select all that apply.''

Since the question was of the format ``select all that apply,''
participants were able to select more than one response and percentages
will not add to 100\%. Results reported below are the percentages of
their respective group (educators or employers) that selected the given
format of instruction. Percentages were utilized due to the difference
in sample size.

Educators and employers were also given the option to enter their own
responses to the question. One employer opted to write in ``Cadaver.''
Two educators entered their own responses with one saying ``rounds'' and
the other saying ``topic seminars do occur with some rotations during
case rounds when dental cases are chosen to present.''

Educators and employers differed in their perceptions of clinical dental
instruction formats completed by early career veterinarians. While a
majority in both groups acknowledged didactic instruction, educators
reported higher rates of wet lab (75\% vs.~46.2\%) and live patient
training (96.4\% vs.~38.5\%) compared to employers. Conversely,
employers more frequently identified simulation training (30.8\%
vs.~14.3\%) than educators.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{Final-Project_files/figure-pdf/formatgraph-1.pdf}}

}

\caption{Perceived Clinical Instruction Formats in Dentistry Completed
by Early Career Veterinarians}

\end{figure}%

Figure 5.1 shows the percentages of each format selected and Table 5.4
shows the p-value associated with performing Fisher's Exact Test on each
format.

Didactic instruction was selected by 57.1\% of educators and 61.5\% of
employers, with no statistically significant difference between the
groups (p=1). There was also no statistically significant difference in
simulation (p=0.237) and wet lab instruction (p=0.0885).

On the other hand, live patient instruction was selected by 96.4\% of
educators, but only 38.5\% of employers. This difference was found to be
statistically significant with a p-value of 0.000105.

``None of these'' was also found to be statistically significant at the
5\% level. No educators selected that none of these formats were
believed to have been used, but 23.1\% of employers selected that none
of the formats were believed to be utilized in the clinical year.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1867}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3200}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.3200}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1733}}@{}}
\caption{Perceived Formats of Clinical Dental Instruction in DVM
Programs}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Format
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\% of Educators Selected
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\% of Employers Selected
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
P-value
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Format
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\% of Educators Selected
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\% of Employers Selected
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
P-value
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Didactic & 57.1 & 61.5 & 1 \\
Simulation & 14.3 & 30.8 & 0.237 \\
Wet Lab & 75.0 & 46.2 & 0.0885 \\
Live Patient & 96.4 & 38.5 & 0.000105 *** \\
None of These & 0.0 & 23.1 & 0.0268 * \\
\end{longtable}

\subsubsection{S6 Do educators and employers differ in their views on
which formats of clinical instruction in dentistry should be required
for DVM students as part of their clinical
training?}\label{s6-do-educators-and-employers-differ-in-their-views-on-which-formats-of-clinical-instruction-in-dentistry-should-be-required-for-dvm-students-as-part-of-their-clinical-training}

In Question \#21 of the employer survey, participants were asked:

• ``Which of the following types of clinical instruction in dentistry do
you think DVM students should be required to complete as part of a DVM
program? Select one response for each of the instructional types listed
below.''

The analogous question for educators appeared as Question \#17 and
stated:

• ``Which of the following types of instruction do you think DVM
students should be required to complete as part of their clinical
training? Select one response for each type of instruction listed
below.''

This question aimed to assess perceptions regarding which types of
dental instruction should be required in the veterinary medical
curriculum across both survey groups. Table 5.3 presents the
Mann--Whitney U-test results, summary statistics, effect sizes, and
ranked-biserial correlation outputs.

\begin{longtable}[t]{>{\centering\arraybackslash}p{1.0in}>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.65in}>{\centering\arraybackslash}p{0.55in}>{\centering\arraybackslash}p{0.75in}>{\centering\arraybackslash}p{1.1in}}
\caption{Mann-Whitney U-Test Results for Clinical Instruction Formats}\\
\toprule
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{Median} & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{ } & \multicolumn{1}{c}{Effect Size} & \multicolumn{1}{c}{ } \\
Skill & Med (Edu) & Med (Emp) & N (Edu / Emp) & P-Value & r\_rb & Interpretation\\
\midrule
Live Patient & 4 & 4 & 28 / 13 & 0.004 ** & -0.35 & Medium negative effect\\
Simulation & 3 & 4 & 20 / 12 & 0.366 & 0.18 & Small positive effect\\
Didactic & 4 & 4 & 23 / 13 & 0.467 & 0.13 & Small positive effect\\
Wet Lab & 4 & 4 & 24 / 13 & 0.658 & 0.05 & Negligible effect\\
\bottomrule
\end{longtable}

The Mann--Whitney U-test revealed a statistically significant difference
(\(p = 0.004\)) between employers and educators when evaluating the
importance of Live Patients. Although both groups reported a median
rating of 4, suggesting similar central tendencies, the ranked-biserial
correlation (\(r_{rb} = -0.35\)) indicates a medium negative effect.
This suggests that employers generally rated Live Patient instruction as
more essential than educators did. The difference in ranking
distributions is statistically meaningful.

No statistically significant differences were found between the groups
regarding the instructional types Simulation (\(p = 0.366\)), Didactic
(\(p = 0.467\)), or Wet Lab (\(p = 0.658\)). The ranked-biserial
correlations for Simulation (\(r_{rb} = 0.18\)) and Didactic
(\(r_{rb} = 0.13\)) were small and positive, indicating a slight
tendency for educators to rate these types of instruction as more
important than employers. The effect size for Wet Lab
(\(r_{rb} = 0.05\)) was negligible. None of these differences reached
statistical significance.

The instructional categories ``None of These'' and ``Other'' were
excluded from Table 5.3 due to insufficient data for statistical
testing.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{Final-Project_files/figure-pdf/s6_diverging_stacked_bar-1.pdf}}

}

\caption{Diverging Stacked Bar Chart of Perceived Importance/Competence
of Clinical Instruction Formats by Group (Educator vs.~Employer).}

\end{figure}%

Figure 5.2 presents the proportional distribution of responses for each
group. While a moderate difference was observed between groups regarding
the use of live patients, the majority of participants in both groups
selected Strongly Agree, and notably, no participants selected Disagree
or Strongly Disagree---indicating strong consensus that live patient
experience should be required in clinical training.

The response distributions for simulation and wet lab instruction appear
nearly identical visually, and statistical analysis confirmed no
significant differences between groups for these skills. Interestingly,
the distribution for didactic instruction looks somewhat different from
those two, despite also showing no statistically significant difference.

This highlights an important point: even when one bar chart appears to
show more variability in proportions than another, the overall ranking
of responses between groups may still be similar. The Mann-Whitney
U-test is designed to detect consistent directional differences in how
groups rank responses. If those patterns are weak, inconsistent, or
cancel each other out, the test will indicate no significant
difference---even when the visualizations suggest otherwise. Differences
in sample size and variability can also exaggerate or smooth over
apparent contrasts that don't reflect meaningful differences in central
tendency.

\subsubsection{S7 Is there a difference between the clinical dentistry
skills that educators report DVM students are learning during their
clinical training and the skills that employers believe recent graduates
have completed as part of their DVM
program?}\label{s7-is-there-a-difference-between-the-clinical-dentistry-skills-that-educators-report-dvm-students-are-learning-during-their-clinical-training-and-the-skills-that-employers-believe-recent-graduates-have-completed-as-part-of-their-dvm-program}

Both educators and employers were asked a question related to skills
learned and practiced during the clinical year.

On question 25 of their survey, employers were asked: ``Which of the
following skills do you think that individuals who graduated with a DVM
degree after May 2021 completed during the clinical training portion of
their DVM program? Select all that apply.''

On question 20 of their survey, educators were asked: ``Which of the
following skills are DVM students at your institution
practicing/learning during the clinical training portion of the DVM
program? Select all that apply.''

Since the question was of the format ``select all that apply,''
participants were able to select more than one response and percentages
will not add to 100\%. Results reported below are the percentages of
their respective group (educators or employers) that selected the given
format of instruction. Percentages were utilized due to the difference
in sample size.

Educators and employers were also given the option to enter their own
responses to the question. No employers entered any text responses. Six
educators entered text responses of the following:

\begin{itemize}
\tightlist
\item
  ``OvaVet gel application, Crown amputation, Sealant application for
  UCF, oral tumor biopsy and excision, orthodontia''
\item
  ``Nerve blocks, barrier sealant and bonded sealant application, jaw
  fracture repair, root canals''
\item
  ``Often- bonded sealants; Sometimes- root canals, restorations, jaw
  fracture repair''
\item
  ``Oral biopsy, root planning, bonded sealants''
\item
  ``extractions only if performed on that patient''
\item
  ``Not all students see all types of extractions''
\end{itemize}

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{Final-Project_files/figure-pdf/question_7a-1.pdf}}

}

\caption{Clinical Training Skills Perceived by Educators vs Employers in
DVM Programs}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.5393}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1685}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1685}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.1236}}@{}}
\caption{Perceived Skills Learned of Clinical Dental Instruction in DVM
Programs}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Skill
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\% of Educators
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\% of Employers
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
P-value
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Skill
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\% of Educators
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
\% of Employers
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
P-value
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Oral Exam/Charting & 92.9 & 69.2 & 0.0685 \\
Radiographic Positioning & 96.4 & 69.2 & 0.0284 * \\
Radiographic Interpretation & 96.4 & 76.9 & 0.0861 \\
Scaling & 96.4 & 61.5 & 0.0084 ** \\
Polishing & 82.1 & 30.8 & 0.00331 ** \\
Canine Closed Extraction & 82.1 & 38.5 & 0.0102 * \\
Feline Closed Extraction & 82.1 & 38.5 & 0.0102 * \\
Canine Open Extraction - Single Root & 82.1 & 38.5 & 0.0102 * \\
Feline Open Extraction - Single Root & 85.7 & 46.2 & 0.0193 * \\
Canine Open Extraction - Canines/Multiple Roots & 85.7 & 46.2 & 0.0193
* \\
Feline Open Extraction - Canines/Multiple Roots & 25.0 & 30.8 & 0.719 \\
Fluoride Treatment & 3.6 & 15.4 & 0.232 \\
None of These & 21.4 & 0.0 & 0.152 \\
\end{longtable}

Figure 5.3 shows the percentage of employers and educators who selected
the given skills and Table 5.6 shows the p-values associated with
Fisher's Exact Test and their significance.

For eleven of the thirteen skills, educators reported a higher
percentage of selection. The two skills for which employers reported
higher perceived learning were feline open extraction - canines/multiple
roots and fluoride treatment.

At the 5\% significance level, the difference in skill selection between
employers and educators was found to be significant for seven skills:

\begin{itemize}
\tightlist
\item
  Radiographic Positioning (p=0.0284)
\item
  Scaling (p=0.0084)
\item
  Polishing (p=0.00331)
\item
  Canine Closed Extraction (p=0.0102)
\item
  Feline Closed Extraction (p=0.0102)
\item
  Canine Open Extraction - Single Root (p=0.0102)
\item
  Feline Open Extraction - Single Root (p=0.0193)
\item
  Canine Open Extraction - Canines/Multiple Roots (p=0.0193)
\end{itemize}

For all skills with statistically significant differences, educators
reported higher percentages than employers.

The largest difference was found in polishing. Educators selected this
skill 82.1\% of the time, while employers selected this skill only
30.8\% of the time. The resulting p-value was 0.00331.

\subsubsection{S8 Do educators and employers differ in their opinions
about which clinical dentistry skills DVM students should be required to
practice or learn during their clinical
training?}\label{s8-do-educators-and-employers-differ-in-their-opinions-about-which-clinical-dentistry-skills-dvm-students-should-be-required-to-practice-or-learn-during-their-clinical-training}

In question \#26 of the employers' version of the survey, participants
were asked:

\begin{itemize}
\tightlist
\item
  ``Which of the following skills do you think that DVM students should
  be required to practice/learn as part of the clinical training portion
  of a DVM program? Select one response for each of the skills listed
  below.''
\end{itemize}

The corresponding question for educators was survey question \#21.

This question aimed to assess opinions on which clinical dentistry
skills should be required in DVM student training. Table 5.5 presents
the Mann--Whitney U-test results, summary statistics, effect sizes, and
ranked-biserial correlation outputs.

\begin{longtable}[t]{>{\centering\arraybackslash}p{1.3in}>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.5in}>{\centering\arraybackslash}p{0.65in}>{\centering\arraybackslash}p{0.55in}>{\centering\arraybackslash}p{0.75in}>{\centering\arraybackslash}p{1.1in}}
\caption{Mann-Whitney U-Test Results for Clinical Procedures}\\
\toprule
\multicolumn{1}{c}{ } & \multicolumn{2}{c}{Median} & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{ } & \multicolumn{1}{c}{Effect Size} & \multicolumn{1}{c}{ } \\
Skill & Med (Edu) & Med (Emp) & N (Edu / Emp) & P-Value & r\_rb & Interpretation\\
\midrule
Feline closed extraction & 4 & 4 & 26 / 11 & 0.064 . & 0.27 & Small positive effect\\
Canine open extraction - Single root & 4 & 4 & 26 / 11 & 0.064 . & 0.27 & Small positive effect\\
Feline open extraction - Single root & 4 & 4 & 26 / 11 & 0.092 . & 0.23 & Small positive effect\\
Canine open extraction - Canines/multiple roots & 4 & 4 & 26 / 11 & 0.092 . & 0.23 & Small positive effect\\
Radiographic interpretation & 4 & 4 & 26 / 11 & 0.261 & 0.12 & Small positive effect\\
\addlinespace
Feline open extraction - Canines/multiple roots & 3 & 4 & 16 / 9 & 0.276 & 0.26 & Small positive effect\\
Canine closed extraction & 4 & 4 & 26 / 11 & 0.437 & 0.11 & Small positive effect\\
Radiographic positioning & 4 & 4 & 26 / 11 & 0.510 & -0.10 & Negligible effect\\
Scaling & 4 & 4 & 26 / 11 & 0.578 & -0.09 & Negligible effect\\
Polishing & 4 & 4 & 26 / 11 & 0.816 & -0.03 & Negligible effect\\
\addlinespace
Oral exam/charting & 4 & 4 & 26 / 11 & 0.829 & 0.03 & Negligible effect\\
\bottomrule
\end{longtable}

Nearly every skill reported a median of 4 with exception to the Feline
Open Extraction - Canines/Multiple Roots whose central tendency was 3.
Note that this exception is the only row that report fewer responses
than the others. Small but consistent differences were found for several
clinical procedures, with educators tending to rate certain skills as
more important than employers.

Specifically, educators rated the following procedures as more important
(higher median values) compared to employers:

\begin{itemize}
\tightlist
\item
  Feline closed extraction (effect size: \(r = 0.27\))
\item
  Canine open extraction -- single root (\(r = 0.27\))
\item
  Feline open extraction -- single root (\(r = 0.23\))
\item
  Canine open extraction -- canines/multiple roots (\(r = 0.23\))
\item
  Feline open extraction -- canines/multiple roots (\(r = 0.26\))
\item
  Radiographic interpretation (\(r = 0.12\))
\item
  Canine closed extraction (\(r = 0.11\))
\end{itemize}

All of these showed small positive effect sizes, indicating that
educators placed slightly more emphasis on these procedures than
employers. However, none of these differences reached conventional
levels of statistical significance (i.e., \(p < 0.05\)), though some
were marginal (\(p ≈ 0.06–0.09\)). Negligible differences were found for
the following skills:

\begin{itemize}
\tightlist
\item
  Radiographic positioning (\(r = -0.10\))
\item
  Scaling (\(r = -0.09\))
\item
  Polishing (\(r = -0.03\))
\item
  Oral examination/charting (\(r = 0.03\))
\end{itemize}

These results suggest that educators and employers generally agreed on
the importance of these particular skills, with only very small or no
measurable differences between groups.

\begin{figure}[H]

{\centering \pandocbounded{\includegraphics[keepaspectratio]{Final-Project_files/figure-pdf/s8_diverging_stacked_bar_final-1.pdf}}

}

\caption{Diverging Stacked Bar Chart of Perceived Competence of Clinical
Procedures by Group (Educator vs.~Employer).}

\end{figure}%

While the effect sizes for several procedures suggest that educators may
place slightly more value on certain clinical extraction skills and
radiographic interpretation than employers, these differences were not
statistically significant. The negligible effect sizes for basic
procedures such as polishing and oral exams indicate a strong consensus
between the two groups regarding these skills. Figure 5.4 shows that the
distribution of responses is broadly similar, and although some
differences exist, they do not reach statistical significance to suggest
meaningful divergence in perceptions of clinical competencies. Notably,
the procedure ``Feline Open Extraction -- Canines/Multiple Roots''
exhibits the greatest variability; however, this may be influenced by
the smaller number of responses for that item.

\section{Discussion/Conclusion}\label{discussionconclusion}

\subsection{Interpretation of Results}\label{interpretation-of-results}

The results across suggest that educators and employers are largely
aligned in their perceptions of dental training and graduate competence,
with no statistically significant differences observed in most areas.
Both groups reported similar beliefs about which skills are taught
preclinically and how many procedures should be completed during
clinical training. However, a few notable trends emerged. Employers
tended to place slightly more importance on teaching advanced
extractions and expected more hands on experience during dentistry
rotations, while educators were slightly more confident in graduates'
ability to interpret radio-graphs. Although these differences were not
always statistically significant, they point to subtle mismatches in
expectations that could be addressed through improved communication and
curriculum transparency.

Another notable finding involved perceptions of live patient instruction
during clinical training. Employers expressed stronger support for live
patient training than educators. In contrast, both groups showed similar
views on wet labs, simulations, and didactic instruction. Overall,
educators and employers largely agreed on the clinical skills that
should be taught in dental training. Although differences were minimal
and statistically non-significant, educators tended to place slightly
greater importance on advanced procedures.

The findings suggest a disconnect between educators and employers in how
they perceive both student preparedness and the methods used to develop
clinical skills. Educators consistently rated students as more
proficient across a range of skills, indicating greater confidence in
the effectiveness of current training approaches. On the other hand,
employers were more cautious in their assessments, which could reflect
different expectations, experiences with new graduates, or varying
standards in clinical practice. The significant difference in views on
instructional formats also highlights a potential misalignment in how
each group understands or values different types of training.
Additionally, the fact that some employers believed none of the
instructional methods were being used raises concerns about transparency
or awareness of educational practices. Overall, these differences point
to a need for stronger collaboration between academic programs and the
veterinary industry to ensure students are being prepared in ways that
are both educationally sound and professionally relevant.

\subsection{Implications of the Study}\label{implications-of-the-study}

The findings of this study have several important implications for
veterinary education and the transition of new graduates into clinical
practice. Overall, the results suggest that educators and small animal
primary care employers are largely aligned in their expectations and
beliefs about dental competencies but key perception gaps remain that
may influence workforce readiness.

First, while both groups generally agreed on the importance of dental
training and reported similar expectations about pre-clinical and
clinical instruction, employers consistently underestimated the extent
of instruction that educators reported providing. This misalignment may
contribute to a lack of confidence in new graduates and increase
reliance on on the job training. Improved transparency and communication
between DVM programs and employers could help align expectations and
strengthen trust in the educational process.

Second, differences in perceived importance of specific skills
especially in areas like complex extractions and fluoride treatments
highlight opportunities to review and potentially revise preclinical
curriculum content. Employers placed greater emphasis on advanced skills
than educators, suggesting a need to evaluate whether current curricula
fully reflect the demands of entry level practice.

Third, the trend for employers to expect a higher number of completed
procedures during clinical rotations, particularly in dentistry specific
settings, points to a possible mismatch in expectations about hands on
experience. Veterinary programs may consider reevaluating case
requirements and ensuring that students receive sufficient procedural
volume to meet clinical demands upon graduation.

Finally, these findings underscore the importance of ongoing
collaboration between academia and clinical practice. By fostering
dialogue between educators and employers, DVM programs can ensure that
their graduates are not only technically competent, but also perceived
as well prepared by those who hire and supervise them. Closing
perception gaps may help reduce onboarding burdens, promote early career
confidence, and ultimately enhance the quality of care delivered in
small animal dentistry.

\subsection{Limitations}\label{limitations}

This study had several limitations that should be considered when
interpreting the results. The sample sizes were relatively small,
particularly for the employer group, which had only 13 respondents after
data cleaning. This limited the statistical power of the analyses and
may reduce the generalizability of the findings. In addition, the uneven
group sizes restricted the types of statistical tests that could be
used.

The recruitment process may have introduced sampling bias. Participants
were recruited through professional networks and personal outreach,
which can result in self selection bias. The employer sample was
disproportionately composed of practice owners compared to national
demographics, which could have skewed the results toward the
perspectives of individuals with more authority or stronger opinions
about training and graduate readiness.

There were also geographic and institutional limitations. Most employer
responses came from practices located on the U.S. East Coast, while
educator responses were more geographically diverse. This imbalance may
limit the applicability of the findings to rural clinics or educational
contexts outside of North America.

All data were self reported which introduces additional concerns such as
variation in how participants interpret survey items. For example, the
concept of ``competency'' may be understood differently across
respondents, even if they selected similar response options on the
Likert scale.

Lastly, missing data was another concern. Several participants did not
complete the entire survey, and certain questions had high rates of
missing or invalid responses. These gaps led to the exclusion of some
data points and may have affected the robustness of the results for
specific comparisons.

\subsection{Recommendations}\label{recommendations}

To improve alignment between veterinary educators and employers, several
strategies should be considered. Communication between veterinary
schools and employers should be strengthened, as employers often
underestimated the level of preclinical and clinical dental training
reported by educators. Programs can address this perception gap by
sharing curricular details and competency expectations through
mechanisms such as externship evaluations, employer advisory boards, or
structured graduate transition reports. Clinical exposure to dental
procedures should also be enhanced, particularly in dentistry rotations,
where employers tended to expect a higher number of completed
procedures. Increasing hands on opportunities in core dental skills,
especially extractions and radiograph interpretation, can better align
training with workplace expectations.

Clarifying learning objectives and defining shared competency standards
is another important step. By standardizing what constitutes competence
in key skills, educators and employers can more consistently assess
graduate preparedness. This is especially relevant for procedures like
open extractions and radiographic interpretation. Additionally,
perceived discrepancies in the importance of certain skills, such as
fluoride treatment and multirooted feline extractions, should be
discussed within curriculum committees and employer advisory groups.
These conversations can help determine whether changes in instruction or
clearer expectation setting are needed. Ongoing dialogue between
veterinary programs and employers through stakeholder surveys,
curriculum reviews, and alumni feedback is essential to keeping
curricula responsive to the evolving demands of clinical practice.

\subsection{Summary of Key Findings}\label{summary-of-key-findings}

There was broad agreement between educators and employers regarding new
graduate competence, curriculum content, and priorities for dental
skills training. However, employers tended to slightly underestimate the
extent of preclinical training that educators reported providing.
Notably, employers placed significantly greater importance on teaching
certain skills preclinically, specifically feline open extractions
involving multiroot teeth and fluoride treatment. Additionally,
employers expected a higher number of completed procedures during
dentistry rotations, indicating stronger expectations for clinical
repetition and hands on experience. Overall, most other comparisons
between the groups revealed no statistically significant differences,
with effect sizes generally small or negligible.

\subsection{Final Thoughts}\label{final-thoughts}

This analysis highlights generally strong alignment between educators
and employers on core dental competencies, but also reveals subtle
perception gaps, particularly in the expected number of clinical
procedures and the importance of teaching advanced extractions and
fluoride treatment. Employers tended to underestimate the scope of
preclinical training and expected more procedural experience during
clinical rotations. These differences, though not always statistically
significant, point to a need for improved communication and transparency
between veterinary programs and the profession to ensure shared
expectations and better prepare graduates for clinical practice.

\section*{Appendix}\label{appendix}
\addcontentsline{toc}{section}{Appendix}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-avma2019}
American Veterinary Medical Association. 2019. {``Census of
Veterinarians Finds Trends, Shortages, Practice Ownership.''} 2019.
\url{https://www.avma.org/javma-news/2019-07-15/census-veterinarians-finds-trends-shortages-practice-ownership}.

\end{CSLReferences}




\end{document}
